### ISSUE TITLE
GISD-Scores auf Basis des Github-Repos nicht nachvollziehbar

### ISSUE THREAD

**Issue by edg-stg** [robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD#1]
Leider lassen sich mit den aktuell bei Github bereitgestellten Dateien die GISD-Scores nicht nachvollziehen.

Ausgangspunkt ist das R-Skript zur Erzeugung der Scores:
https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/main/Kontextmaterialien/Syntax/GISD_Generate_Release.R

- [ ] die Dateipfade im Skript sind nicht relativ zum Repo, sondern wahrscheinlich zu einer lokalen Version (behebbar, Beispiel: https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/cabd33279811ef1e4c4546f2a7bfc7ec91b93add/Kontextmaterialien/Syntax/GISD_Generate_Release.R#L39)
- [ ] die NUTS2-Daten von INKAR sind nicht Teil des Repos, werden im Skript aber benötigt (https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/cabd33279811ef1e4c4546f2a7bfc7ec91b93add/Kontextmaterialien/Syntax/GISD_Generate_Release.R#L112), es fehlen dadurch insbesondere die Variablen BevoelkerungmitakadAbschluss und BevoelkerungohneAbschluss. Eventuell werden diese Variablen aber gar nicht benötigt, ob die NUTS2-Daten entbehrlich sind, lässt sich mit dem aktuellen Stand der Skriptdokumentation nicht feststellen. Im Folgenden sind die Zeilen 112-128 nicht ausführbar.
- [ ] ein schnell behebbarer Schreibfehler sorgt dafür, dass Zeile 130ff nicht ausführbar ist (Kreisbene statt Kreisebene, https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/cabd33279811ef1e4c4546f2a7bfc7ec91b93add/Kontextmaterialien/Syntax/GISD_Generate_Release.R#L130)
- [ ] ungültiger Logarithmus sorgt für NA-Werte (https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/cabd33279811ef1e4c4546f2a7bfc7ec91b93add/Kontextmaterialien/Syntax/GISD_Generate_Release.R#L177)
- [ ] in den Funktionen adj_G8_Jahr und OW werden Regressionskoeffizienten aus einem Dataframe über ihre indizierten Positionen aufgerufen, bei OW führt dies zu einer Fehlermeldung (Zeile 18 und 23 einer Tabelle mit 14 Zeilen werden angesprochen: https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/cabd33279811ef1e4c4546f2a7bfc7ec91b93add/Kontextmaterialien/Syntax/GISD_Generate_Release.R#L232 Ob dies Folge eines der oben stehenden Probleme ist, kann ich nicht einschätzen). Besser wäre es, die Koeffizienten über ihre Namen anzusprechen.
- [ ] Abschnitt VI (PLZ-Datensätze) komplett nicht ausführbar, weil kein Ordner SHP bzw shapefiles im Repo vorhanden sind (https://github.com/robert-koch-institut/German_Index_of_Socioeconomic_Deprivation_GISD/blob/cabd33279811ef1e4c4546f2a7bfc7ec91b93add/Kontextmaterialien/Syntax/GISD_Generate_Release.R#L560)

**Comment by Skeiwalkski** [comment]
Lieber Herr Steiger,
Vielen Dank für die Hinweise. Wir werden demnächst eine angepasste Version der Syntax für das GISD Release 2022 v1 hochladen. Mittlerweile liegt auch die Genehmigung für die Bereitstellung der Rohdaten der Statistik der Bundesagentur für Arbeit vor, sodass wir mit der Anpassung auch die vollständigen Rohdaten bereitstellen können. Eine Ausnahme bilden die Daten der PLZ-Gemeindekennzifferzuordnung. 
Beste Grüße

Niels Michalski
